Repository openshift/managed-velero-operator, pull requests merged in 2019-11, with the labels that each got.

#21 New Feature, s3 bucket tagging for velero backups.
  deploy/credential_request.yaml
  pkg/controller/velero/s3.go
  pkg/controller/velero/velero.go
  pkg/s3/bucket.go
Labels: approved, lgtm, size/M

#22 Creating tags is now a generic function that can be reused in the future should it be needed.
  pkg/s3/bucket.go
Labels: approved, lgtm, size/S

#23 Update Velero to 1.1.0 and operator-sdk to 0.12.0
  .golangci.yml
  build/Dockerfile
  cmd/manager/main.go
  deploy/crds/managed.openshift.io_v1alpha1_velero_cr.yaml
  deploy/crds/managed.openshift.io_veleros_crd.yaml
  go.mod
  go.sum
  pkg/apis/managed/v1alpha1/register.go
  pkg/apis/managed/v1alpha1/velero_types.go
  pkg/apis/managed/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/managed/v1alpha1/zz_generated.openapi.go
  pkg/controller/velero/controller.go
  pkg/controller/velero/s3.go
  pkg/controller/velero/velero.go
  pkg/util/platform/platform.go
  pkg/util/platform/platform_test.go
  tools.go
Labels: approved, lgtm, size/XL
