Repository openshift/managed-velero-operator, pull requests merged in 2020-03, with the labels that each got.

#38 Fix image building
  build/Dockerfile
  standard.mk
Labels: approved, lgtm, size/S

#37 use chinese mirror for the veleo image in AWS China
  pkg/controller/velero/velero.go
Labels: approved, lgtm, size/S

#39 use the default partitionID for the region which defined in the aws sdk
  pkg/controller/velero/velero.go
Labels: approved, lgtm, size/S

#42 Add version file for golangci-lint
  .golangciversion
Labels: approved, lgtm, size/XS

#43 Update to ubi8
  build/Dockerfile
Labels: approved, lgtm, size/XS

#44 Added APAC & EMEA to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#41 Update standard.mk with CONTAINER_ENGINE options
  standard.mk
Labels: approved, lgtm, size/S

#45 Bump golangci-lint to v1.23.8
  .golangciversion
Labels: approved, lgtm, size/XS

#47 Add readme node about pushing to your personal Quay repo
  README.md
Labels: approved, lgtm

#50 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, lgtm

#51 Update OWNERS
  OWNERS
Labels: approved, lgtm

#49 Update velero/operator-sdk/platformstatus
  cmd/manager/main.go
  deploy/cluster_config_v1_reader_role.yaml
  deploy/cluster_config_v1_reader_role_binding.yaml
  deploy/cluster_role.yaml
  deploy/crds/managed.openshift.io_veleros_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  go.mod
  go.sum
  pkg/apis/managed/v1alpha1/zz_generated.openapi.go
  pkg/controller/velero/controller.go
  pkg/controller/velero/velero.go
  pkg/util/platform/platform.go
  pkg/velero/crds.go
  project.mk
  version/version.go
Labels: approved, lgtm

#46 OSD-2620: Create Storage Driver Interface
  go.mod
  go.sum
  pkg/apis/managed/v1alpha1/reconcile.go
  pkg/controller/velero/controller.go
  pkg/controller/velero/s3.go
  pkg/storage/s3/bucket.go
  pkg/storage/s3/bucket_test.go
  pkg/storage/s3/client.go
  pkg/storage/s3/s3.go
  pkg/storage/storage.go
Labels: approved, lgtm, tide/merge-method-squash

#48 veleroDeployment: Create a Service and ServiceMonitor
  cmd/manager/main.go
  deploy/role.yaml
  go.mod
  pkg/controller/velero/velero.go
Labels: approved, lgtm

#53 Fix CRD name in role
  deploy/role.yaml
Labels: approved, lgtm

#54 Fix some log lines
  go.mod
  go.sum
  pkg/storage/s3/s3.go
Labels: approved, lgtm
