Repository openshift/managed-velero-operator, pull requests merged in 2020-01, with the labels that each got.

#30 Move velero deployment to infra nodes
  deploy/operator.yaml
  pkg/controller/velero/velero.go
Labels: approved, lgtm, size/M

#28 Enable recovery using existing bucket
  cmd/manager/main.go
  deploy/credential_request.yaml
  pkg/controller/velero/controller.go
  pkg/controller/velero/s3.go
  pkg/s3/bucket.go
  pkg/s3/client.go
  pkg/util/platform/platform.go
  pkg/util/platform/platform_test.go
Labels: approved, lgtm, size/L

#32 Use an interface for the S3 client
  pkg/controller/velero/s3.go
  pkg/s3/bucket.go
  pkg/s3/bucket_test.go
  pkg/s3/client.go
Labels: approved, lgtm, size/XL

#33 Simplify error handling logic around bucket tags
  pkg/s3/bucket.go
  pkg/s3/bucket_test.go
Labels: approved, lgtm, size/M
